#!/bin/bash

# Checks if the patch version number commited to package.json on the current
# branch is less than the one commmitted to master and if so bumps the package
# version by one patch number and commits it

set -o nounset
set -o errexit

print_patch() {
  awk -F '.' '/version/{print $3+0}'
}

MASTER="$(git show origin/master:package.json | print_patch)";
CURRENT="$(cat package.json | print_patch)";

git fetch origin master
if [[ $MASTER -ge $CURRENT ]]; then
  perl -i -pe 's/(version": "(\d+\.)*)(\d+)(.*)/$1.($3+1).$4/e' package.json
  git commit package.json --no-verify -m "bump version" > /dev/null
  echo "bumped and commited patch version"
fi
