#!/bin/bash

# Watches for changes and runs a command
#
# Watches current directory by default by can pass a file name or a directory
# to watch
# Depends on inotify-tools

set -o nounset
set -o errexit

## VARIABLES
FORMAT="%%w%%f modified"
FILE="."
COMMAND=$@

## FUNCTIONS
usage() {
  printf "Usage: reflex [file|directory] <command>\n"
  exit 1
}

print() {
  printf "\033[1;33m[reflex]\033[0m $1"
}

run() {
  print "running $COMMAND\n"
  eval "$COMMAND"
}

## ARG CHECK

if [[ $# == 0 ]]; then usage; fi
if [[ $# == 2 ]]; then
  FILE=$1
  COMMAND="${@:2}"
  if [[ ! -e $FILE ]]; then usage; fi
fi

## MAIN

# Run command once to ensure validity
if ! run; then exit $?; fi

# Loop
while true; do
  inotifywait -qr --event modify --format "$(print $FORMAT)" $FILE
  run
done
